# Generated by Django 4.1 on 2022-12-01 09:44

from django.db import migrations
import user_auth.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', user_auth.managers.CustomUserManager()),
            ],
        ),
    ]
