# Generated by Django 4.1 on 2022-10-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='otp_request_id',
        ),
        migrations.AddField(
            model_name='otp',
            name='code',
            field=models.IntegerField(default=667827),
        ),
    ]
