# Generated by Django 4.1 on 2022-10-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_otp_otp_request_id_otp_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
