# Generated by Django 4.1 on 2022-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='uid',
            field=models.UUIDField(default=0, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
