# Generated by Django 4.1 on 2022-10-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_myuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='id',
            new_name='uid',
        ),
    ]
