# Generated by Django 4.1 on 2022-10-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_otp_requested_by_remove_otp_time_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='time_requested',
        ),
    ]
