# Generated by Django 4.1.2 on 2022-11-09 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('storage', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('computer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computers.computer')),
                ('size', models.CharField(max_length=100)),
            ],
            bases=('computers.computer',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('computer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computers.computer')),
                ('screen_resolution', models.CharField(max_length=100)),
                ('battery_capacity', models.CharField(max_length=100)),
                ('battery_life', models.IntegerField()),
            ],
            bases=('computers.computer',),
        ),
    ]
