# Generated by Django 4.1 on 2022-12-01 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('size', models.CharField(max_length=100)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('battey', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('connectivity', models.CharField(max_length=50)),
                ('video_output', models.CharField(max_length=50)),
                ('audio_output', models.CharField(max_length=50)),
            ],
            bases=('shop.product',),
        ),
    ]
