# Generated by Django 4.1 on 2022-12-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='os',
            field=models.CharField(default='Windows 10', max_length=50),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='ram',
            field=models.CharField(default='8GB', max_length=10),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='storage',
            field=models.CharField(default='512GB SSD', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='battery',
            field=models.CharField(default='5000mAh', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='camera',
            field=models.CharField(default='720p', max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='os',
            field=models.CharField(default='Windows 10', max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.CharField(default='8GB', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.CharField(default='512GB SSD', max_length=10),
        ),
    ]
