# Generated by Django 4.1 on 2022-12-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='battey',
            new_name='battery',
        ),
    ]
