# Generated by Django 4.1.2 on 2022-11-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_remove_computer_id_computer_product_ptr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='model_name',
            new_name='model',
        ),
        migrations.AlterField(
            model_name='computer',
            name='memory',
            field=models.IntegerField(choices=[('Small', 4), ('Medium', 8), ('Large', 16), ('Extreme', 32)]),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage',
            field=models.IntegerField(choices=[('Small', 256), ('Medium', 512), ('Large', 1024), ('Extreme', 2048)]),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='size',
            field=models.CharField(choices=[('Small', 'SFF'), ('Mini', 'Mini Tower'), ('Mid', 'Mid Tower'), ('Big', 'Full Tower')], max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_resolution',
            field=models.CharField(choices=[('WXGA', '1280x800'), ('HD', '1366x768'), ('HD+', '1600x900'), ('FHD', '1920x1080'), ('QHD', '2560x1440'), ('QHD+', '3200x1800'), ('UHD', '3840x2160')], max_length=100),
        ),
    ]
