# Generated by Django 4.1 on 2022-12-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=20)),
                ('image', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
