# Generated by Django 4.1 on 2022-12-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='battery',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablet',
            name='camera',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
